apiVersion: v1
kind: Service
metadata:
  name: mongo-headless-service
spec:
  selector:
    app: mongo
  clusterIP: None # headless service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

